# @package _global_

env:
  observation_conversion:
    train_move:
      _target_: maze_flatland.space_interfaces.observation_conversion.simple.SimpleObservationConversion
      serialize_representation: False
