# @package model
_target_: maze.perception.models.custom_model_composer.CustomModelComposer

distribution_mapper_config: []

policy:
  _target_: maze.perception.models.policies.ProbabilisticPolicyComposer
  substeps_with_separate_agent_nets: []
  networks:
    train_move:
      _target_: 'maze.perception.models.built_in.flatten_concat.FlattenConcatPolicyNet'
      non_lin: 'torch.nn.Tanh'
      hidden_units: [512, 256]

critic:
  _target_: maze.perception.models.critics.StateCriticComposer
  networks:
    train_move:
      _target_: maze.perception.models.built_in.flatten_concat.FlattenConcatStateValueNet
      non_lin: 'torch.nn.Tanh'
      hidden_units: [512, 256]
